// Auto-generated by PyBridge — do not edit


export interface CreateUserInput {
  name: string;
  email: string;
  age?: number | null;
}

export interface User {
  id: string;
  name: string;
  email: string;
  age?: number | null;
}

export interface GetUserInput {
  id: string;
}

export interface AvatarUpload {
  user_id: string;
  file: File;
}

export interface ChatInput {
  prompt: string;
}

export interface ProcedureErrors {
  "users.get": "NOT_FOUND";
}

export interface AppRouter {
  users: {
    create: (input: CreateUserInput) => Promise<User>;
    /** @throws PyBridgeError<"NOT_FOUND"> */
    get: (input: GetUserInput) => Promise<User>;
    list: () => Promise<User[]>;
    me: () => Promise<User>;
    upload_avatar: (input: AvatarUpload) => Promise<unknown>;
  };
  health: {
    ping: () => Promise<string>;
  };
  ticks: {
    stream: { subscribe: () => Subscription<void> };
  };
  chat: {
    /** Token-by-token streaming over SSE (think LLM completions). */
    complete: { stream: (input: ChatInput) => Stream<string> };
  };
}

export type PyBridgeError<Code extends string = string> = Error & { code: Code; data?: unknown };

type ProcedureCall = (input?: unknown) => Promise<unknown>;

export interface ClientOptions {
  headers?: () => Record<string, string> | Promise<Record<string, string>>;
  fetch?: typeof fetch;
  wsFactory?: (url: string) => WebSocket;
  /** Per request `credentials`; set to `"include"` for cross-origin cookie auth. */
  credentials?: RequestCredentials;
  /** Name of the CSRF cookie. If set, its value is echoed in `X-CSRF-Token`. */
  csrfCookie?: string;
}

export interface Subscription<T> {
  next(): Promise<IteratorResult<T>>;
  return(): Promise<IteratorResult<T>>;
  [Symbol.asyncIterator](): AsyncIterator<T>;
}

export interface Stream<T> {
  [Symbol.asyncIterator](): AsyncIterator<T>;
  cancel(): void;
}

export function createClient<T = AppRouter>(baseUrl: string, opts: ClientOptions = {}): T {
  const doFetch = opts.fetch ?? fetch;
  const base = baseUrl.replace(/\/$/, "");

  const callProc = async (path: string[], input: unknown): Promise<unknown> => {
    const url = `${base}/rpc/${path.join(".")}`;
    const extra = opts.headers ? await opts.headers() : {};
    const hasFile = containsFile(input);
    let body: BodyInit | undefined;
    const headers: Record<string, string> = { ...extra };
    if (opts.csrfCookie) {
      const csrf = readCookie(opts.csrfCookie);
      if (csrf) headers["x-csrf-token"] = csrf;
    }
    if (hasFile) {
      body = toFormData(input);
    } else if (input !== undefined) {
      body = JSON.stringify(input);
      headers["content-type"] = "application/json";
    }
    const res = await doFetch(url, { method: "POST", headers, body, credentials: opts.credentials });
    const text = await res.text();
    const data = text ? JSON.parse(text) : null;
    if (!res.ok) {
      const err = (data && (data as any).error) ?? { code: "HTTP_ERROR", message: res.statusText };
      throw makeError(err);
    }
    return data;
  };

  const subscribe = (path: string[], input: unknown): Subscription<unknown> => {
    const wsUrl = `${base.replace(/^http/, "ws")}/ws`;
    const ws = opts.wsFactory ? opts.wsFactory(wsUrl) : new WebSocket(wsUrl);
    const id = Math.random().toString(36).slice(2);
    const queue: IteratorResult<unknown>[] = [];
    let pending: ((v: IteratorResult<unknown>) => void) | null = null;
    let closed = false;

    const push = (v: IteratorResult<unknown>) => {
      if (pending) { pending(v); pending = null; } else { queue.push(v); }
    };

    ws.onopen = () => ws.send(JSON.stringify({ type: "subscribe", id, path: path.join("."), input }));
    ws.onmessage = (ev) => {
      const m = JSON.parse(ev.data);
      if (m.id !== id) return;
      if (m.type === "next") push({ value: m.value, done: false });
      else if (m.type === "complete") { closed = true; push({ value: undefined, done: true }); }
      else if (m.type === "error") { closed = true; push({ value: undefined, done: true }); }
    };
    ws.onclose = () => { closed = true; push({ value: undefined, done: true }); };

    const iter: Subscription<unknown> = {
      next() {
        if (queue.length) return Promise.resolve(queue.shift()!);
        if (closed) return Promise.resolve({ value: undefined, done: true });
        return new Promise((resolve) => { pending = resolve; });
      },
      return() {
        if (!closed) { ws.close(); closed = true; }
        return Promise.resolve({ value: undefined, done: true });
      },
      [Symbol.asyncIterator]() { return iter as AsyncIterator<unknown>; },
    };
    return iter;
  };

  const streamCall = (path: string[], input: unknown): Stream<unknown> => {
    const url = `${base}/rpc/${path.join(".")}`;
    const ac = new AbortController();
    let cancelled = false;

    async function* run(): AsyncGenerator<unknown> {
      const extra = opts.headers ? await opts.headers() : {};
      const headers: Record<string, string> = {
        accept: "text/event-stream",
        "content-type": "application/json",
        ...extra,
      };
      if (opts.csrfCookie) {
        const csrf = readCookie(opts.csrfCookie);
        if (csrf) headers["x-csrf-token"] = csrf;
      }
      const res = await doFetch(url, {
        method: "POST",
        headers,
        body: input === undefined ? "" : JSON.stringify(input),
        credentials: opts.credentials,
        signal: ac.signal,
      });
      if (!res.ok || !res.body) {
        const text = await res.text();
        const data = text ? JSON.parse(text) : null;
        throw makeError((data && (data as any).error) ?? { code: "HTTP_ERROR", message: res.statusText });
      }
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buf = "";
      try {
        while (!cancelled) {
          const { value, done } = await reader.read();
          if (done) return;
          buf += decoder.decode(value, { stream: true });
          let idx: number;
          while ((idx = buf.indexOf("

")) >= 0) {
            const raw = buf.slice(0, idx);
            buf = buf.slice(idx + 2);
            const ev = parseSSE(raw);
            if (!ev) continue;
            if (ev.event === "next") yield ev.data;
            else if (ev.event === "complete") return;
            else if (ev.event === "error") throw makeError(ev.data ?? { code: "ERROR", message: "stream failed" });
          }
        }
      } finally {
        try { reader.releaseLock(); } catch {}
      }
    }

    const gen = run();
    return {
      [Symbol.asyncIterator]() { return gen; },
      cancel() { cancelled = true; ac.abort(); },
    };
  };

  const make = (path: string[]): any => {
    const fn: any = (input?: unknown) => callProc(path, input);
    fn.subscribe = (input?: unknown) => subscribe(path, input);
    fn.stream = (input?: unknown) => streamCall(path, input);
    return new Proxy(fn, {
      get: (target, prop: string) => {
        if (prop === "subscribe") return target.subscribe;
        if (prop === "stream") return target.stream;
        if (typeof prop !== "string" || prop === "then") return undefined;
        return make([...path, prop]);
      },
    });
  };

  return make([]) as T;
}

export function batch(baseUrl: string, calls: { path: string; input?: unknown }[], opts: ClientOptions = {}): Promise<({ result: unknown } | { error: { code: string; message: string; data?: unknown } })[]> {
  const doFetch = opts.fetch ?? fetch;
  const url = `${baseUrl.replace(/\/$/, "")}/rpc/_batch`;
  return (async () => {
    const extra = opts.headers ? await opts.headers() : {};
    const csrfHeader: Record<string, string> = {};
    if (opts.csrfCookie) {
      const csrf = readCookie(opts.csrfCookie);
      if (csrf) csrfHeader["x-csrf-token"] = csrf;
    }
    const res = await doFetch(url, {
      method: "POST",
      headers: { "content-type": "application/json", ...extra, ...csrfHeader },
      body: JSON.stringify(calls),
      credentials: opts.credentials,
    });
    if (!res.ok) throw makeError({ code: "HTTP_ERROR", message: res.statusText });
    return res.json();
  })();
}

function containsFile(v: unknown): boolean {
  if (v == null || typeof v !== "object") return false;
  if (typeof File !== "undefined" && v instanceof File) return true;
  if (Array.isArray(v)) return v.some(containsFile);
  return Object.values(v as Record<string, unknown>).some(containsFile);
}

function toFormData(input: unknown): FormData {
  const fd = new FormData();
  const meta: Record<string, unknown> = {};
  if (input && typeof input === "object" && !Array.isArray(input)) {
    for (const [k, v] of Object.entries(input as Record<string, unknown>)) {
      if (typeof File !== "undefined" && v instanceof File) fd.append(k, v);
      else if (Array.isArray(v) && v.every((x) => typeof File !== "undefined" && x instanceof File)) {
        for (const f of v) fd.append(k, f as File);
      } else {
        meta[k] = v;
      }
    }
  }
  fd.append("__json__", JSON.stringify(meta));
  return fd;
}

function parseSSE(raw: string): { event: string; data: any } | null {
  let event = "message";
  const dataLines: string[] = [];
  for (const line of raw.split("
")) {
    if (line.startsWith("event:")) event = line.slice(6).trim();
    else if (line.startsWith("data:")) dataLines.push(line.slice(5).trim());
  }
  const dataStr = dataLines.join("
");
  if (!dataLines.length) return { event, data: null };
  try { return { event, data: JSON.parse(dataStr) }; } catch { return { event, data: dataStr }; }
}

function readCookie(name: string): string | null {
  if (typeof document === "undefined") return null;
  const match = document.cookie.match(new RegExp("(?:^|; )" + name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "=([^;]*)"));
  return match ? decodeURIComponent(match[1]) : null;
}

function makeError(err: { code: string; message: string; data?: unknown }): PyBridgeError {
  const e = new Error(err.message) as PyBridgeError;
  e.code = err.code;
  if (err.data !== undefined) e.data = err.data;
  return e;
}
